"""created table

Revision ID: fe3db72990ae
Revises: 
Create Date: 2020-01-31 17:20:49.836192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3db72990ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_n', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=140), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('s_n')
    )
    op.create_index(op.f('ix_register_request_time'), 'register', ['request_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_request_time'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
